fastlane_version "2.148.0"
default_platform(:ios)

platform :ios do

  $derivedDataPath = './DerivedData/'
  $uiTestScheme = 'GithubActionDemo'

  desc 'Build iOS simulator app'
  lane :build_simulator_app do
    gym(
      scheme: $uiTestScheme,
      configuration: "Debug",
      skip_archive: true, 
      skip_package_ipa: true,
      destination: "generic/platform=iOS Simulator",
      derived_data_path: $derivedDataPath,
      xcargs: "-sdk iphonesimulator ONLY_ACTIVE_ARCH=YES build-for-testing COMPILER_INDEX_STORE_ENABLE=NO"
    )
  end

  desc 'Install pods'
  lane :install_pods do
    cocoapods(
      clean_install: true,
      try_repo_update_on_error: true,
      use_bundle_exec: true
    )
  end  

end
