fastlane_version "2.148.0"
default_platform(:ios)

platform :ios do

  desc 'Build iOS simulator app'
  lane :build_simulator_app do
    gym(
      scheme: 'GithubActionDemo',
      configuration: "Debug",
      skip_archive: true, 
      skip_package_ipa: true,
      destination: "generic/platform=iOS Simulator",
      derived_data_path: './DerivedData/',
      xcargs: "-sdk iphonesimulator ONLY_ACTIVE_ARCH=YES build-for-testing COMPILER_INDEX_STORE_ENABLE=NO"
    )
    sh('mkdir -p ../Builds && cp -r ../DerivedData/Build/Products/Debug-iphonesimulator/GithubActionDemo.app $_')
  end

  desc 'Install pods'
  lane :install_pods do
    cocoapods(
      clean_install: true,
      try_repo_update_on_error: true,
      use_bundle_exec: true
    )
  end  

  desc 'Clear caches'
  lane :clear_caches do
    sh('rm -rf ../DerivedData')
    sh('rm -rf ../Pods')
    sh('rm -rf ../Builds')
  end  

  desc 'Run tests in single thread'
  lane :test_single_mode do
    run_tests(
      scheme: 'GithubActionDemo', 
      derived_data_path: './DerivedData/',
      test_without_building: true,
      skip_build: true,
      reset_simulator: true,
      result_bundle: true,
      output_directory: './Builds/',
      device: 'iPhone 8',
      disable_slide_to_type: true,
      disable_concurrent_testing: true
  )
  end  

end
