name: Just PWD

on:
  workflow_dispatch


jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Get source code 🚀
      uses: actions/checkout@v2
        
    - name: Run simple command
      run: |
        pwd
        
